// <auto-generated />
using EasyFinder.DbConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyFinder.Migrations
{
    [DbContext(typeof(MottuDbContext))]
    partial class MottuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyFinder.Model.Andar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero_andar")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_ANDAR");

                    b.Property<int>("bloco_id")
                        .HasColumnType("int")
                        .HasColumnName("GALPAO_ID");

                    b.HasKey("Id");

                    b.ToTable("ANDAR");
                });

            modelBuilder.Entity("EasyFinder.Model.Bloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Letra_bloco")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LETRA_BLOCO");

                    b.Property<int>("Patio_id")
                        .HasColumnType("int")
                        .HasColumnName("PATIO_ID");

                    b.HasKey("Id");

                    b.ToTable("BLOCO");
                });

            modelBuilder.Entity("EasyFinder.Model.Galpao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome_galpao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_GALPAO");

                    b.HasKey("Id");

                    b.ToTable("GALPAO");
                });

            modelBuilder.Entity("EasyFinder.Model.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHASSI");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PLACA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATUS");

                    b.Property<int>("Vaga_id")
                        .HasColumnType("int")
                        .HasColumnName("VAGA_ID");

                    b.HasKey("Id");

                    b.ToTable("MOTO");
                });

            modelBuilder.Entity("EasyFinder.Model.Patio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Andar_id")
                        .HasColumnType("int")
                        .HasColumnName("ANDAR_ID");

                    b.Property<int>("Numero_patio")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_PATIO");

                    b.HasKey("Id");

                    b.ToTable("PATIO");
                });

            modelBuilder.Entity("EasyFinder.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USUARIO");

                    b.HasKey("Id");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("EasyFinder.Model.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bloco_id")
                        .HasColumnType("int")
                        .HasColumnName("BLOCO_ID");

                    b.Property<int>("Numero_vaga")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_VAGA");

                    b.HasKey("Id");

                    b.ToTable("VAGA");
                });
#pragma warning restore 612, 618
        }
    }
}
