// <auto-generated />
using EasyFinder.DbConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EasyFinder.Migrations
{
    [DbContext(typeof(MottuDbContext))]
    [Migration("20250523032217_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyFinder.Model.Andar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero_andar")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO_ANDAR");

                    b.Property<int>("bloco_id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GALPAO_ID");

                    b.HasKey("Id");

                    b.ToTable("ANDAR");
                });

            modelBuilder.Entity("EasyFinder.Model.Bloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Letra_bloco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LETRA_BLOCO");

                    b.Property<int>("Patio_id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIO_ID");

                    b.HasKey("Id");

                    b.ToTable("BLOCO");
                });

            modelBuilder.Entity("EasyFinder.Model.Galpao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome_galpao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_GALPAO");

                    b.HasKey("Id");

                    b.ToTable("GALPAO");
                });

            modelBuilder.Entity("EasyFinder.Model.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CHASSI");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PLACA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<int>("Vaga_id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VAGA_ID");

                    b.HasKey("Id");

                    b.ToTable("MOTO");
                });

            modelBuilder.Entity("EasyFinder.Model.Patio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Andar_id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANDAR_ID");

                    b.Property<int>("Numero_patio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO_PATIO");

                    b.HasKey("Id");

                    b.ToTable("PATIO");
                });

            modelBuilder.Entity("EasyFinder.Model.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bloco_id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BLOCO_ID");

                    b.Property<int>("Numero_vaga")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO_VAGA");

                    b.HasKey("Id");

                    b.ToTable("VAGA");
                });
#pragma warning restore 612, 618
        }
    }
}
